sudo: false
language: clojure
script: ./test.sh
install:
  - mkdir ~/boot
  - export PATH=~/boot:$PATH
  - curl -L https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh -o ~/boot/boot
  - chmod +x ~/boot/boot
jdk:
  - openjdk7
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.boot/cache
  - $HOME/bin
